const GET_PRODUCT_PENDING = "GET_PRODUCT_PENDING";
const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

const POST_PRODUCT_PENDING = "POST_PRODUCT_PENDING";
const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
const POST_PRODUCT_ERROR = "POST_PRODUCT_ERROR";
